// Generated by CoffeeScript 1.4.0
(function() {
  var app;

  app = angular.module('main', []);

  app.controller('MainCtrl', function($scope, $http) {
    $scope.posts = [{}];
    $http.get('someUrl.html').then(function(response) {
      return $scope.posts = response.data;
    });
    $scope.create = function(post) {
      return $http.post('someUrl.html', JSON.stringify({
        'user': this.userName,
        'content': post.content
      })).then(function(response) {
        $scope.posts.push(response.data);
        return post.content = '';
      });
    };
    $scope.signedOut = false;
    return $scope.userName = '';
  });

}).call(this);
